# Generated by Django 3.2.4 on 2021-07-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210720_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Harsh',
            new_name='Project',
        ),
    ]
